// Auto-generated from country color files
// Generated on: 2025-11-21T22:31:08.597Z
// Source: country colors/
//
// Total countries: 152
// Colors from files: 116
// Fallback colors: 36

/**
 * Defines the basic data structure for a country
 */
export interface CountryData {
    name: string;
    color: string;
}

/**
 * Master map of all countries in the game (HOI4 tags)
 * Key: 3-letter HOI4 country tag (e.g., "USA", "PRC", "ENG")
 * Value: CountryData with display name and map color
 */
export const countryData = new Map<string, CountryData>([
    ["AFG", { name: "Afghanistan", color: "#40a0a7" }],
    ["ALB", { name: "Albania", color: "#952d66" }],
    ["ALG", { name: "Algeria", color: "#9163b4" }],
    ["ANG", { name: "Angola", color: "#71fa32" }],
    ["ARG", { name: "Argentina", color: "#919dec" }],
    ["ARM", { name: "Armenia", color: "#891f71" }],
    ["AST", { name: "Australia", color: "#398f61" }],
    ["AUS", { name: "Austria", color: "#e0e4ff" }],
    ["AZR", { name: "Azerbaijan", color: "#7c9450" }],
    ["BAN", { name: "Bangladesh", color: "#0000f3" }],
    ["BEL", { name: "Belgium", color: "#c1ab08" }],
    ["BHU", { name: "Bhutan", color: "#9882bf" }],
    ["BLR", { name: "Belarus", color: "#74500a" }],
    ["BOL", { name: "Bolivia", color: "#ffb488" }],
    ["BOS", { name: "Bosnia", color: "#c3ff70" }],
    ["BOT", { name: "Botswana", color: "#b76232" }],
    ["BRA", { name: "Brazil", color: "#4c913f" }],
    ["BRD", { name: "BRD", color: "#2a55ac" }],
    ["BRM", { name: "Burma", color: "#00c800" }],
    ["BUL", { name: "Bulgaria", color: "#427145" }],
    ["CAM", { name: "Cambodia", color: "#6caa0a" }],
    ["CAN", { name: "Canada", color: "#773027" }],
    ["CAR", { name: "CAR", color: "#2eb267" }],
    ["CBV", { name: "CBV", color: "#5428b8" }],
    ["CHA", { name: "Chad", color: "#62358a" }],
    ["CHI", { name: "China", color: "#fff4be" }],
    ["CHL", { name: "Chile", color: "#9b656b" }],
    ["CMR", { name: "Cameroon", color: "#8c3a26" }],
    ["COL", { name: "Colombia", color: "#debb5b" }],
    ["COS", { name: "Costa Rica", color: "#2c1ecc" }],
    ["CRO", { name: "Croatia", color: "#f54646" }],
    ["CUB", { name: "Cuba", color: "#c32c58" }],
    ["CYP", { name: "CYP", color: "#d6d917" }],
    ["CZE", { name: "Czech Republic", color: "#aabefa" }],
    ["DAH", { name: "DAH", color: "#18dcbf" }],
    ["DEN", { name: "Denmark", color: "#99745d" }],
    ["DOM", { name: "Dominican Republic", color: "#ff000d" }],
    ["ECU", { name: "Ecuador", color: "#f99262" }],
    ["EGY", { name: "Egypt", color: "#e6e646" }],
    ["ELS", { name: "El Salvador", color: "#b330df" }],
    ["ENG", { name: "United Kingdom", color: "#c9385d" }],
    ["EQG", { name: "EQG", color: "#d74f3c" }],
    ["ERI", { name: "Eritrea", color: "#1c8f8a" }],
    ["EST", { name: "Estonia", color: "#4c9dc3" }],
    ["ETH", { name: "Ethiopia", color: "#dc3a38" }],
    ["FIN", { name: "Finland", color: "#cdd4e4" }],
    ["FRA", { name: "France", color: "#5071f0" }],
    ["GAB", { name: "Gabon", color: "#1e320a" }],
    ["GAM", { name: "GAM", color: "#5ad380" }],
    ["GEO", { name: "Georgia", color: "#c16b3d" }],
    ["GER", { name: "Germany", color: "#4c6179" }],
    ["GHA", { name: "Ghana", color: "#0b55da" }],
    ["GNA", { name: "GNA", color: "#922629" }],
    ["GNB", { name: "GNB", color: "#255593" }],
    ["GRE", { name: "Greece", color: "#5db5e3" }],
    ["GUA", { name: "Guatemala", color: "#31209d" }],
    ["HAI", { name: "Haiti", color: "#2c9630" }],
    ["HOL", { name: "HOL", color: "#2daf1d" }],
    ["HON", { name: "Honduras", color: "#3cb11b" }],
    ["HUN", { name: "Hungary", color: "#f97e62" }],
    ["ICE", { name: "Iceland", color: "#647daf" }],
    ["INS", { name: "Indonesia", color: "#e6aaa0" }],
    ["IRE", { name: "Ireland", color: "#509f5a" }],
    ["IRQ", { name: "Iraq", color: "#b27263" }],
    ["ISR", { name: "Israel", color: "#5477a8" }],
    ["ITA", { name: "Italy", color: "#437f3f" }],
    ["IVO", { name: "IVO", color: "#cd4f13" }],
    ["JAP", { name: "Japan", color: "#ffbfbf" }],
    ["JOR", { name: "Jordan", color: "#efefb6" }],
    ["KAZ", { name: "Kazakhstan", color: "#1709f3" }],
    ["KEN", { name: "Kenya", color: "#948f4e" }],
    ["KOR", { name: "KOR", color: "#1dcfe7" }],
    ["KOS", { name: "Kosovo", color: "#3974d3" }],
    ["KUW", { name: "Kuwait", color: "#fb612a" }],
    ["KYR", { name: "KYR", color: "#a3cf3a" }],
    ["LAO", { name: "Laos", color: "#44aa5a" }],
    ["LAT", { name: "Latvia", color: "#705a57" }],
    ["LBA", { name: "LBA", color: "#e98525" }],
    ["LEB", { name: "Lebanon", color: "#82963c" }],
    ["LIB", { name: "Libya", color: "#c8b45a" }],
    ["LIT", { name: "Lithuania", color: "#dbdb77" }],
    ["LUX", { name: "Luxembourg", color: "#41afb3" }],
    ["MAC", { name: "Macedonia", color: "#f9e06d" }],
    ["MAD", { name: "Madagascar", color: "#f06e5a" }],
    ["MAL", { name: "Malaysia", color: "#a8aa00" }],
    ["MEX", { name: "Mexico", color: "#689853" }],
    ["MLI", { name: "Mali", color: "#9a78b3" }],
    ["MLW", { name: "MLW", color: "#59cfb2" }],
    ["MNT", { name: "Montenegro", color: "#fa515a" }],
    ["MOL", { name: "Moldova", color: "#f0ff70" }],
    ["MON", { name: "Mongolia", color: "#a1be66" }],
    ["MOR", { name: "Morocco", color: "#4bb7e4" }],
    ["MRT", { name: "MRT", color: "#655ad3" }],
    ["MZB", { name: "MZB", color: "#9f3f14" }],
    ["NEP", { name: "Nepal", color: "#c40020" }],
    ["NGA", { name: "NGA", color: "#263e92" }],
    ["NGR", { name: "NGR", color: "#161ca2" }],
    ["NIC", { name: "Nicaragua", color: "#7e9622" }],
    ["NKR", { name: "North Korea", color: "#28015a" }],
    ["NMB", { name: "NMB", color: "#7c209d" }],
    ["NOR", { name: "Norway", color: "#6f4747" }],
    ["NZL", { name: "New Zealand", color: "#9e6529" }],
    ["OMA", { name: "Oman", color: "#a6bfa7" }],
    ["PAK", { name: "Pakistan", color: "#1777f3" }],
    ["PAN", { name: "Panama", color: "#b88523" }],
    ["PAR", { name: "Paraguay", color: "#3971e4" }],
    ["PER", { name: "Peru", color: "#c4bdcc" }],
    ["PHI", { name: "Philippines", color: "#22bf5b" }],
    ["PNG", { name: "PNG", color: "#3cc81e" }],
    ["POL", { name: "Poland", color: "#c55c6a" }],
    ["POR", { name: "Portugal", color: "#277446" }],
    ["PRC", { name: "PRC", color: "#3f1ec8" }],
    ["PRU", { name: "PRU", color: "#ba2c87" }],
    ["RAJ", { name: "British Raj", color: "#aa0a0a" }],
    ["RCG", { name: "RCG", color: "#4131d3" }],
    ["ROM", { name: "Romania", color: "#ebd85c" }],
    ["RUS", { name: "Russia", color: "#7d0d18" }],
    ["RWA", { name: "RWA", color: "#86e628" }],
    ["SAF", { name: "South Africa", color: "#40d48b" }],
    ["SAU", { name: "Saudi Arabia", color: "#abbe98" }],
    ["SEN", { name: "Senegal", color: "#36beb3" }],
    ["SIA", { name: "Siam", color: "#d841d1" }],
    ["SIE", { name: "SIE", color: "#dd3cab" }],
    ["SLO", { name: "Slovakia", color: "#36a79c" }],
    ["SLV", { name: "Slovenia", color: "#68d6ff" }],
    ["SOL", { name: "SOL", color: "#ec3293" }],
    ["SOM", { name: "Somalia", color: "#3a5d76" }],
    ["SPR", { name: "Spain", color: "#f2cd5e" }],
    ["SRB", { name: "Serbia", color: "#5a506e" }],
    ["SUD", { name: "Sudan", color: "#ee998a" }],
    ["SWE", { name: "Sweden", color: "#2484f7" }],
    ["SWI", { name: "Switzerland", color: "#210e13" }],
    ["SYR", { name: "Syria", color: "#646496" }],
    ["TAJ", { name: "TAJ", color: "#85dd4b" }],
    ["TMS", { name: "TMS", color: "#bfd459" }],
    ["TOG", { name: "TOG", color: "#a07d13" }],
    ["TUN", { name: "Tunisia", color: "#a9197b" }],
    ["TUR", { name: "Turkey", color: "#1e8e94" }],
    ["TZN", { name: "TZN", color: "#996b1e" }],
    ["UAE", { name: "United Arab Emirates", color: "#d28371" }],
    ["UGA", { name: "Uganda", color: "#302b116" }],
    ["UKR", { name: "Ukraine", color: "#005ab9" }],
    ["URG", { name: "URG", color: "#9511b6" }],
    ["USA", { name: "USA", color: "#b1167c" }],
    ["UZB", { name: "Uzbekistan", color: "#2b838f" }],
    ["VEN", { name: "Venezuela", color: "#ce1126" }],
    ["VIN", { name: "VIN", color: "#be4113" }],
    ["VOL", { name: "VOL", color: "#2fa78f" }],
    ["WES", { name: "WES", color: "#d312a5" }],
    ["YEM", { name: "Yemen", color: "#e75823" }],
    ["ZAM", { name: "Zambia", color: "#5326fa" }],
    ["ZIM", { name: "Zimbabwe", color: "#00d25a" }]
]);
